PE-21 | Backend fully conntected. Springboot connected with MongoDB.
ProjectEureka/project-eureka-spring pull request #1
Opened 2020-12-02 21:45 UTC by davidsquines

What I did:

- Created basis for our backend.

- Connected Springboot Application with MongoDB.

- Created "User" entity with "firstname" and "lastname" values only.

How to do:

- Download Mongo Compass UI. This will be needed to visualize the data table. 

- After compass has been downloaded, enter the correct connection string for our database. Contact Tony or me for the connection string. 

- Checkout and pull from the branch "PE-21-SetUpMongo.

-Navigate to the **src/main/resources/application.properties**. Inside you should see a single url starting with spring.data.mongo.uri. You will need to change the fields "<user>, <password>, and <Auth_DB>" to the correct values. **Ensure that when you replace these values, delete the "<" and ">" from the final input fields**. Contact Tony N. or I for these fields. 
-Navigate to the file "ProjectEurekaBackendApplication.java" and find the following area
<img width="409" alt="Screen Shot 2020-12-02 at 1 32 44 PM" src="https://user-images.githubusercontent.com/48227740/100933916-deaa9680-34a2-11eb-8e1f-27e612cdb9d7.png">
- Change the values for the first and last name of the new users to be inserted into the database. 

- Run the application by pressing the "play" on Visual Studio Code  or "run" button on your IDE
<img width="380" alt="Screen Shot 2020-12-02 at 1 34 22 PM" src="https://user-images.githubusercontent.com/48227740/100934095-1a456080-34a3-11eb-8eb5-8b91dde2e41c.png">
- The new users should be inputed into the database. Verify via the Mongo Compass app by navigating to the collection "Users" in the "Project-Eureka" database. Your compass should now contain the new users you inputed. 
<img width="1035" alt="Screen Shot 2020-12-02 at 1 43 28 PM" src="https://user-images.githubusercontent.com/48227740/100934982-5d540380-34a4-11eb-8a2d-243a1c87f359.png">

2020-12-07 02:18 UTC, MaxLian11 commented
Works totally fine on my end. The only thing I would change is to keep Models, Repositories and Services in separate folders, as we are going to have more tables in the future. Controller folder can also be created for future development

2020-12-07 02:26 UTC, MaxLian11 requested changes
Please read the comment and create new folders

2020-12-07 02:49 UTC, dominikyz approved these changes
Code looks good to me. As Max suggested separate into different folders. Great job!

2020-12-07 09:22 UTC, tonynguyen98 requested changes
It's working on my end! I also agree on the two other reviews, please move these files into proper directories.

2020-12-07 09:22 UTC, tonynguyen98 commented on src/main/java/com/ProjectEureka/backend/User.java
> +import lombok.Setter;
Delete these.

2021-01-18 03:43 UTC, MaxLian11 approved these changes
Looks good now

2021-01-18 03:59 UTC, tonynguyen98 approved these changes
Good work! It's working as expected.

2021-01-18 03:59 UTC, merged