PE-53 | Created a View Model for Profile Page
ProjectEureka/project-eureka-spring pull request #9
Opened 2021-03-03 21:32 UTC by tonynguyen98

**What I Did:** 
- Added a `findByUserId` to both `QuestionRepository` and `AnswerRepository`.
- Created a new Profile Object that contains data from `User`, `Question` and `Answer`.
- Create the service that will aggregate `User`, `Questions` (by userId ) and `Answers` (by userId) into a single model for the front-end.
- Created a controller that will send this model out via HTTP GET.

**How to Test:**
1. Create a new User using the HTTP PUT controller created by @ayeejane.
```json
{
"firstName" : "Jennie",
"lastName" : "Kim",
"firebaseUuid" : "123456",
"email" : "jenniekim@yahoo.com",
"city" : "Los Angeles",
"category" : ["Technology"],
"pictureUrl" : "hellokitty.com",
"role" : 0,
"rating" : 9
}
```
2. Create a couple Questions using HTTP PUT controller created by @dominikyz.  IMPORTANT: Make sure you use the id provided in step 1 for the `user_id` in Questions.
```json
{
    "title": "TestRecord2",
    "questionDate": "2012-04-23T18:25:43.511Z",
    "description": "Description goes here",
    "category": "science",
    "status": 1,
    "visible": 1,
    "userId": "ID FROM STEP 1"
}
```
3. Now, create a couple more Questions, but use a random `user_id`!!!
4. Create a couple Answers using HTTP PUT controller created by @davidsquines.  IMPORTANT: Make sure you use the id provided in step 1 for the `user_id` in Answers.
```json
{
    "mediaUrls": [
        "www.google.com", 
        "www.csun.edu"
        ],
    "answerDate": "2012-04-23T18:25:43.511+00:00",
    "questionId": 7,
    "userId": "ID FROM STEP 1"
}
```
5. Now, create a couple more Answers, but use a random `user_id`!!!
6. Using Postman, hit HTTP GET `localhost:8080/v1/profile/{USER ID}`. You should a `ok` response that will return the user and questions/answers that contain only the correct `user_id`!.

2021-03-06 18:29 UTC, txt020 commented
@tonynguyen98 For the PUT request, is the URL the same as the GET request?

2021-03-06 18:38 UTC, tonynguyen98 commented
> @tonynguyen98 For the PUT request, is the URL the same as the GET request?

Apologies, I meant POST request and the routes for those would be `localhost:8080/v1/users`, `localhost:8080/v1/questions` and `localhost:8080/v1/answers`. In that order respectively.

2021-03-07 03:34 UTC, dominikyz approved these changes
Code looks great. CRUD operations work like a charm! Awesome job!

2021-03-07 21:50 UTC, ayeejane requested changes

2021-03-07 21:50 UTC, ayeejane commented on src/main/java/com/ProjectEureka/backend/services/ProfileServiceImpl.java
> +            return new Profile(user.get(), questionsByUserId, answersByUserId);
A profile might not have both questions and answers

2021-03-08 00:11 UTC, davidsquines approved these changes
Works as intended

2021-03-08 02:48 UTC, txt020 approved these changes
Everything looks good and it works as intended.

2021-03-08 03:21 UTC, ayeejane approved these changes
Works beautifully now!

2021-03-08 03:27 UTC, merged